apiVersion: v1
kind: Secret
metadata:
  name: booking-postgres-secret
  namespace: eventticketing
type: Opaque
stringData:
  POSTGRES_DB: etdb-bookings
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
