apiVersion: v1
kind: Secret
metadata:
  name: event-postgres-secret
  namespace: eventticketing
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: etdb-events
