apiVersion: v1
kind: Secret
metadata:
  name: sales-postgres-secret
  namespace: eventticketing
type: Opaque
stringData:
  POSTGRES_DB: etdb-sales
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
