apiVersion: v1
kind: Secret
metadata:
  name: ticket-postgres-secret
  namespace: eventticketing
type: Opaque
stringData:
  POSTGRES_DB: etdb-tickets
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
