apiVersion: v1
kind: Secret
metadata:
  name: user-postgres-secret
  namespace: eventticketing
type: Opaque
stringData:
  POSTGRES_DB: etdb-users
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
