apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
  namespace: eventticketing
data:
  SPRING_APPLICATION_NAME: api-gateway
  USER_SERVICE_URI: http://user-service:8080
  EVENT_SERVICE_URI: http://event-service:8080
  BOOKING_SERVICE_URI: http://booking-service:8080
  TICKET_SERVICE_URI: http://ticket-service:8080
  SALES_SERVICE_URI: http://sales-service:8080
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
