apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-configmap
  namespace: eventticketing
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://ticket-postgres:5432/etdb-tickets
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/eventticketingmongo?authSource=admin
  SPRING_CASSANDRA_CONTACT_POINTS: cassandra:9042
  SPRING_CASSANDRA_PORT: "9042"
  SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
  SPRING_CASSANDRA_KEYSPACE_NAME: eventticketingks
  SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra:9042
  SPRING_DATA_CASSANDRA_PORT: "9042"
  SPRING_DATA_CASSANDRA_LOCAL_DATACENTER: datacenter1
  SPRING_DATA_CASSANDRA_KEYSPACE_NAME: eventticketingks
  FEIGN_BOOKING_SERVICE_URL: http://booking-service:8080
  FEIGN_EVENT_SERVICE_URL: http://event-service:8080
