apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: eventticketing
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/etdb-users
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  FEIGN_BOOKING_SERVICE_URL: http://booking-service:8080
  LOKI_URL: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
