apiVersion: v1
kind: Service
metadata:
  name: booking-postgres
  namespace: eventticketing
spec:
  clusterIP: None
  selector:
    app: booking-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
