apiVersion: v1
kind: Service
metadata:
  name: event-postgres
  namespace: eventticketing
spec:
  clusterIP: None
  selector:
    app: event-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
