apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: eventticketing
  labels:
    app: sales-service
spec:
  type: ClusterIP
  selector:
    app: sales-service
  ports:
    - name: http
      port: 8080
      targetPort: http
